<?php
use Illuminate\Database\Seeder;
use Winwins\User;
use Winwins\Model\UserDetail;

class UsersTableSeeder extends Seeder {

    public function run() {
        DB::table('users')->delete();

        $user = new User();
        $user->email = 'mariana.berruezo@gmail.com'; 
        $user->username = 'mariana.berruezo@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Manuna'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'Entusiasta exploradora de los para quÃ©s de la Web'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'user_168_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'xavadu@gmail.com'; 
        $user->username = 'xavadu@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Du'; 
        $detail->name = 'Xava'; 
        $detail->birthdate = '1982-01-16'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rey.nico@gmail.com'; 
        $user->username = 'rey.nico@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rey'; 
        $detail->name = 'NicolÃ¡s'; 
        $detail->birthdate = '1990-10-22'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'stedesco@paginar.net'; 
        $user->username = 'stedesco@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Tedesco'; 
        $detail->name = 'Sebas'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sporta@paginar.net'; 
        $user->username = 'sporta@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Falso'; 
        $detail->name = 'JosÃ©'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@hotmail.com'; 
        $user->username = 'marojenieva@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Paginar'; 
        $detail->name = 'MJN'; 
        $detail->birthdate = '1977-10-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'raygiubilo@hotmail.com'; 
        $user->username = 'raygiubilo@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Giubilo'; 
        $detail->name = 'Ray'; 
        $detail->birthdate = '1977-10-22'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Beer'; 
        $detail->name = 'Andy'; 
        $detail->birthdate = '1980-02-20'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldo.tuc.ar@gmail.com'; 
        $user->username = 'arnaldo.tuc.ar@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'del carmen'; 
        $detail->name = 'arnaldo'; 
        $detail->birthdate = '1984-10-17'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rgil@paginar.net'; 
        $user->username = 'rgil@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gil Giuliano'; 
        $detail->name = 'Rodrigo'; 
        $detail->birthdate = '1984-10-17'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lfontan@paginar.net'; 
        $user->username = 'lfontan@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fontan'; 
        $detail->name = 'Liliana'; 
        $detail->birthdate = '1976-12-21'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'gilgiulianobackup@gmail.com'; 
        $user->username = 'gilgiulianobackup@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gil Giuliano'; 
        $detail->name = 'Rodrigo'; 
        $detail->birthdate = '1976-12-21'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@yahoo.com'; 
        $user->username = 'marojenieva@yahoo.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'n'; 
        $detail->name = 'mj'; 
        $detail->birthdate = '1977-10-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marioanibalmarquez@gmail.com'; 
        $user->username = 'marioanibalmarquez@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'M'; 
        $detail->name = 'Mario'; 
        $detail->birthdate = '1980-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnieva@paginar.net'; 
        $user->username = 'mjnieva@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Paginar'; 
        $detail->name = 'Mjn'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javiromerofoto@gmail.com'; 
        $user->username = 'javiromerofoto@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rom'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-10-23'; 
        $detail->sex = 'M'; 
        $detail->about = 'Soy diseÃ±ador grÃ¡fico, especializado en diseÃ±o web y tambiÃ©n fotÃ³grafo de moda.'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'user_195_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@gmail.com'; 
        $user->username = 'marojenieva@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nieva'; 
        $detail->name = 'MarÃ­a JosÃ©'; 
        $detail->birthdate = '1977-10-23'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnpaginar@yahoo.com.ar'; 
        $user->username = 'mjnpaginar@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'hotmail paginar'; 
        $detail->name = 'mjn'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'dariozaj@gmail.com'; 
        $user->username = 'dariozaj@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Zajdenberg'; 
        $detail->name = 'Dario'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'oqtuvre@hotmail.com'; 
        $user->username = 'oqtuvre@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Stewart-Usher'; 
        $detail->name = 'Lenny'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javirangel56@gmail.com'; 
        $user->username = 'javirangel56@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez Manteola'; 
        $detail->name = 'Javier Angel'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@me.com'; 
        $user->username = 'javierangel56@me.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@gmail.com'; 
        $user->username = 'marojenieva@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nieva'; 
        $detail->name = 'MarÃ­a JosÃ©'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lilianafontan@hotmail.com'; 
        $user->username = 'lilianafontan@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'FontÃ¡n'; 
        $detail->name = 'Liliana'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel@fibertel.com.ar'; 
        $user->username = 'javierangel@fibertel.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Angel Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lfontan@paginar.com'; 
        $user->username = 'lfontan@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fontan'; 
        $detail->name = 'Lili'; 
        $detail->birthdate = '1994-12-21'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fetraverso@yahoo.com.ar'; 
        $user->username = 'fetraverso@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Traverso'; 
        $detail->name = 'Fernando Jorge'; 
        $detail->birthdate = '1956-11-09'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanmayol@gmail.com'; 
        $user->username = 'juanmayol@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Mayol'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sricciardi@fibertel.com.ar'; 
        $user->username = 'sricciardi@fibertel.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Lima'; 
        $detail->name = 'Sebastian'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'test@mail.com'; 
        $user->username = 'test@mail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'test'; 
        $detail->name = 'test'; 
        $detail->birthdate = '2000-04-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'test2@mail.com'; 
        $user->username = 'test2@mail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'test 2'; 
        $detail->name = 'test 2'; 
        $detail->birthdate = '1998-05-22'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sostele@outlook.com'; 
        $user->username = 'sostele@outlook.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Stele'; 
        $detail->name = 'Sonia'; 
        $detail->birthdate = '1980-07-08'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'haze.cardoso@gmail.com'; 
        $user->username = 'haze.cardoso@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cardoso'; 
        $detail->name = 'Carlos'; 
        $detail->birthdate = '1980-07-08'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ovidionason@gmail.com'; 
        $user->username = 'ovidionason@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nason'; 
        $detail->name = 'Ovidio '; 
        $detail->birthdate = '1966-11-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ovidionason1976@gmail.com'; 
        $user->username = 'ovidionason1976@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nason'; 
        $detail->name = 'Ovidio'; 
        $detail->birthdate = '1956-10-29'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aldobonzi1976@gmail.com'; 
        $user->username = 'aldobonzi1976@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Bonzi'; 
        $detail->name = 'Aldo'; 
        $detail->birthdate = '1956-10-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aldobonzi1976@gmail.com'; 
        $user->username = 'aldobonzi1976@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Bonzi'; 
        $detail->name = 'Aldo'; 
        $detail->birthdate = '1956-10-29'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'alainrouge1976@gmail.com'; 
        $user->username = 'alainrouge1976@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rouge'; 
        $detail->name = 'Alain'; 
        $detail->birthdate = '1986-09-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'alainrouge1976@gmail.com'; 
        $user->username = 'alainrouge1976@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rouge'; 
        $detail->name = 'Alain'; 
        $detail->birthdate = '1996-12-29'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'revistamatinee@gmail.com'; 
        $user->username = 'revistamatinee@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Matinee'; 
        $detail->name = 'Marteena'; 
        $detail->birthdate = '1996-12-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'revistamatinee@gmail.com'; 
        $user->username = 'revistamatinee@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Matinee'; 
        $detail->name = 'Valenteena'; 
        $detail->birthdate = '1996-12-29'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'jesusguiraud@yahoo.com.ar'; 
        $user->username = 'jesusguiraud@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'guiraud'; 
        $detail->name = 'jesus '; 
        $detail->birthdate = '1977-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'karaokedos@hotmail.com'; 
        $user->username = 'karaokedos@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ponce'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1977-10-15'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperez@hotmail.com'; 
        $user->username = 'juanperez@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1980-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@paginar.com'; 
        $user->username = 'lvommaro@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = '1982-12-20'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@paginar.net'; 
        $user->username = 'lvommaro@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo A.'; 
        $detail->birthdate = '1982-12-20'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'karaokedos@hotmail.com'; 
        $user->username = 'karaokedos@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Hamada'; 
        $detail->name = 'Fabiana'; 
        $detail->birthdate = '1981-12-13'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'acostajuan2013@twitter.com'; 
        $user->username = 'acostajuan2013@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juan Acosta'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = '1981-12-13'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@gmail.com'; 
        $user->username = 'lvommaro@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = '1981-12-13'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'agastiazoro@paginar.com'; 
        $user->username = 'agastiazoro@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Ana'; 
        $detail->birthdate = '1982-04-17'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'matiasche@gmail.com'; 
        $user->username = 'matiasche@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Che'; 
        $detail->name = 'Matias'; 
        $detail->birthdate = '1984-02-19'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'nabebis@yahoo.com'; 
        $user->username = 'nabebis@yahoo.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Navas'; 
        $detail->name = 'Bea'; 
        $detail->birthdate = '1957-07-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'demians@digbang.com'; 
        $user->username = 'demians@digbang.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Schnaidman'; 
        $detail->name = 'Demian'; 
        $detail->birthdate = '1975-08-03'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ebox@jarawi.com'; 
        $user->username = 'ebox@jarawi.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Box'; 
        $detail->name = 'Enrique'; 
        $detail->birthdate = '1975-03-20'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@hotmail.com'; 
        $user->username = 'sivocarina@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '2013-07-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@yahoo.com'; 
        $user->username = 'sivocarina@yahoo.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '1968-07-22'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'jnassif@paginar.com'; 
        $user->username = 'jnassif@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nassif'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-03-21'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.com'; 
        $user->username = 'mcarena@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Matias'; 
        $detail->birthdate = '1968-04-12'; 
        $detail->sex = 'M'; 
        $detail->about = 'EstudiÃ³ DiseÃ±o Industrial en la Universidad de Buenos Aires (UBA). EntendiÃ³ la importancia de Internet desde sus comienzos y en 1994 fundÃ³ Paginar junto a SebastiÃ¡n Tedesco. Desde entonces no ha parado. Confiesa que disfruta de la familia, los amigos, la buena cocina y el golf.'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'user_253_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'test@paginar.com'; 
        $user->username = 'test@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'paginar'; 
        $detail->name = 'test'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnieva@paginar.com'; 
        $user->username = 'mjnieva@paginar.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'FalcÃ³n'; 
        $detail->name = 'Marianita'; 
        $detail->birthdate = '2000-01-19'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'afernandez@paginar.com_1'; 
        $user->username = 'afernandez@paginar.com_1'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'del carmen'; 
        $detail->name = 'arnaldo'; 
        $detail->birthdate = '1988-08-11'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mh@illuminatilab.com'; 
        $user->username = 'mh@illuminatilab.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Hegouaburu'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1982-10-07'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1982-10-07'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanaperezmilenaria2013@yahoo.com.ar'; 
        $user->username = 'juanaperezmilenaria2013@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juana'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->username = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Pedro'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JuanaPe20169106@twitter.com'; 
        $user->username = 'JuanaPe20169106@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juana'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fhamada@paginar.net'; 
        $user->username = 'fhamada@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Acosta'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1990-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmilenario@yahoo.com.ar'; 
        $user->username = 'juanperezmilenario@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'yahoo!'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juan Perez'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = '1990-01-01'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmilenario@gmail.com'; 
        $user->username = 'juanperezmilenario@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1990-01-01'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmillonario@yahoo.com.ar'; 
        $user->username = 'juanperezmillonario@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'NuÃ±ez AgÃ¼ero'; 
        $detail->name = 'IÃ±aki'; 
        $detail->birthdate = '1971-09-18'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->username = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Paula'; 
        $detail->birthdate = '1995-11-19'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldoprog@hotmail.com'; 
        $user->username = 'arnaldoprog@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = '1979-10-17'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JohnPerez201320@twitter.com'; 
        $user->username = 'JohnPerez201320@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1979-10-17'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mariagomezmillonaria@gmail.com'; 
        $user->username = 'mariagomezmillonaria@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1999-09-18'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@gmail.com'; 
        $user->username = 'sivocarina@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '1999-01-07'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mariojuarezmenor@gmail.com'; 
        $user->username = 'mariojuarezmenor@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juarez'; 
        $detail->name = 'Mario'; 
        $detail->birthdate = '1999-09-18'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sandrastun@gmail.com'; 
        $user->username = 'sandrastun@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'AstÃºn'; 
        $detail->name = 'Sandra Paola'; 
        $detail->birthdate = '1975-12-04'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cesaralexisdiaz@gmail.com'; 
        $user->username = 'cesaralexisdiaz@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'diaz'; 
        $detail->name = 'cesar alexis'; 
        $detail->birthdate = '1975-12-04'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JLuzbelito@twitter.com'; 
        $user->username = 'JLuzbelito@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'N.'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1975-12-04'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'bowieagency@twitter.com'; 
        $user->username = 'bowieagency@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Agency'; 
        $detail->name = 'Bowie'; 
        $detail->birthdate = '1975-12-04'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'Jorgemantovani@hotmail.com'; 
        $user->username = 'Jorgemantovani@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Mantovani'; 
        $detail->name = 'Jorge'; 
        $detail->birthdate = '1958-12-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'kbzndiaz69@yahoo.com.ar'; 
        $user->username = 'kbzndiaz69@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Diaz'; 
        $detail->name = 'Cesar Alexis'; 
        $detail->birthdate = '1969-01-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'raygiubilo@gmail.com'; 
        $user->username = 'raygiubilo@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'giubilo'; 
        $detail->name = 'Raymond'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'Virtginia@twitter.com'; 
        $user->username = 'Virtginia@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ginia'; 
        $detail->name = 'Virt'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fabianahamada@gmail.com'; 
        $user->username = 'fabianahamada@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Prueba'; 
        $detail->name = 'Faby'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'nocualquiera@gmail.com'; 
        $user->username = 'nocualquiera@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-06-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'virginiapizzaferri@gmail.com'; 
        $user->username = 'virginiapizzaferri@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-06-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@a.com'; 
        $user->username = 'a@a.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'ss'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'b@a.com'; 
        $user->username = 'b@a.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Maria'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'c@b.com'; 
        $user->username = 'c@b.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@b.com'; 
        $user->username = 'a@b.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'a'; 
        $detail->name = 'ss'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mspentito@yahoo.com.ar'; 
        $user->username = 'mspentito@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Pentito'; 
        $detail->name = 'MarÃ­a Soledad'; 
        $detail->birthdate = '1978-10-15'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'vip@ideadeliveryla.com'; 
        $user->username = 'vip@ideadeliveryla.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Pizza'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-02-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marianadumas@fibertel.com.ar'; 
        $user->username = 'marianadumas@fibertel.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Dumas'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1963-10-17'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldex@twitter.com'; 
        $user->username = 'arnaldex@twitter.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = '1963-10-17'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'vgaibisso@yahoo.com.ar'; 
        $user->username = 'vgaibisso@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gaibisso'; 
        $detail->name = 'Viviana'; 
        $detail->birthdate = '1954-09-09'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mnvercellino@hotmail.com'; 
        $user->username = 'mnvercellino@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ve.'; 
        $detail->name = 'Nawel'; 
        $detail->birthdate = '1910-09-11'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@a.com.ar'; 
        $user->username = 'a@a.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'a'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cristobalalfonzo@outlook.com'; 
        $user->username = 'cristobalalfonzo@outlook.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alfonzo'; 
        $detail->name = 'Cristobal'; 
        $detail->birthdate = '1996-11-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javiernassif@hotmail.com'; 
        $user->username = 'javiernassif@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nassif'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-03-21'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.net'; 
        $user->username = 'mcarena@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Mati'; 
        $detail->birthdate = '1968-12-04'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rozashome@gmail.com'; 
        $user->username = 'rozashome@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Barton'; 
        $detail->name = 'Ed'; 
        $detail->birthdate = '1944-02-14'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'edunick@gmail.com'; 
        $user->username = 'edunick@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cortez'; 
        $detail->name = 'Eduardo'; 
        $detail->birthdate = '1979-03-26'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'edunick@gmail.com'; 
        $user->username = 'edunick@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cortez'; 
        $detail->name = 'Eduardo'; 
        $detail->birthdate = '1979-03-26'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cperez2603@hotmail.com'; 
        $user->username = 'cperez2603@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ctez'; 
        $detail->name = 'Ealx'; 
        $detail->birthdate = '1982-11-01'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'eruete@iae.edu.ar'; 
        $user->username = 'eruete@iae.edu.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ruete GÃ¼emes'; 
        $detail->name = 'Ernesto'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldo.tuc.ar@gmail.com'; 
        $user->username = 'arnaldo.tuc.ar@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldoprog@hotmail.com'; 
        $user->username = 'arnaldoprog@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'yahoo!'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Arnaldo Fernandez'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmillonario@yahoo.com.ar'; 
        $user->username = 'juanperezmillonario@yahoo.com.ar'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'NuÃ±ez AgÃ¼ero'; 
        $detail->name = 'IÃ±aki'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.net'; 
        $user->username = 'mcarena@paginar.net'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Mati'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aito0077@gmail.com'; 
        $user->username = 'aito0077@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Garcia'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@gmail.com'; 
        $user->username = 'javierangel56@gmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'daniel.riosmoreno@hotmail.com'; 
        $user->username = 'daniel.riosmoreno@hotmail.com'; 
        $user->password = '$2y$10$0cUA3QaSO9oTc27fpr1hHOS0hdofKTJrUOis5TAN4/MDh9ZauQiDC'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rios'; 
        $detail->name = 'Daniel'; 
        $detail->birthdate = '1986-11-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@mac.com'; 
        $user->username = 'javierangel56@mac.com'; 
        $user->password = 'ec297842d8eab5ba2e283814f582857b'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier Angel '; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aito77@twitter.com'; 
        $user->username = 'aito77@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'aito77'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'prueba@gmail.com'; 
        $user->username = 'prueba@gmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Apellido'; 
        $detail->name = 'Nombre'; 
        $detail->birthdate = '1976-10-15'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'gabybreg'; 
        $user->username = 'gabybreg'; 
        $user->password = '6acdbee23196e4acff4a0df631034a89'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Brenes'; 
        $detail->name = 'Gaby'; 
        $detail->birthdate = '1990-03-30'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'myberru'; 
        $user->username = 'myberru'; 
        $user->password = '36f2e31cf9edbf4da4c6aea420894d94'; 
        $user->facebook = 'winwins'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'martin@martincaputto.com'; 
        $user->username = 'martin@martincaputto.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Caputto'; 
        $detail->name = 'MartÃ­n'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'smoreno@paginar.net'; 
        $user->username = 'smoreno@paginar.net'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Moreno'; 
        $detail->name = 'Silvina'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lmhenriquezm@gmail.com'; 
        $user->username = 'lmhenriquezm@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Henriquez'; 
        $detail->name = 'Luis'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'placeholder-square.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'interactivista@twitter.com'; 
        $user->username = 'interactivista@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->active = 1;
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Interactivista'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();

    }

}

