<?php
use Illuminate\Database\Seeder;
use Winwins\User;
use Winwins\Model\UserDetail;

class UsersTableSeeder extends Seeder {

    public function run() {
        DB::table('users')->delete();

        $user = new User();
        $user->email = 'mariana.berruezo@gmail.com'; 
        $user->username = 'mariana.berruezo@gmail.com'; 
        $user->password = '36f2e31cf9edbf4da4c6aea420894d94'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Manuna'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'Entusiasta exploradora de los para quÃ©s de la Web'; 
        $detail->photo = 'user_168.jpg'; 
        $detail->cover_photo = 'user_168_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'xavadu@gmail.com'; 
        $user->username = 'xavadu@gmail.com'; 
        $user->password = '42486a985b03a51f7dfa6f696fb5c8cb'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Du'; 
        $detail->name = 'Xava'; 
        $detail->birthdate = '1982-01-16'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_172.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rey.nico@gmail.com'; 
        $user->username = 'rey.nico@gmail.com'; 
        $user->password = 'fd3c6b796a5844172f55efdb6163fb29'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rey'; 
        $detail->name = 'NicolÃ¡s'; 
        $detail->birthdate = '1990-10-22'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_174.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'stedesco@paginar.net'; 
        $user->username = 'stedesco@paginar.net'; 
        $user->password = 'c289942cd01f95dcdfa2fc287113eff2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Tedesco'; 
        $detail->name = 'Sebas'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_175.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sporta@paginar.net'; 
        $user->username = 'sporta@paginar.net'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Falso'; 
        $detail->name = 'JosÃ©'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_179.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@hotmail.com'; 
        $user->username = 'marojenieva@hotmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Paginar'; 
        $detail->name = 'MJN'; 
        $detail->birthdate = '1977-10-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_182.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'raygiubilo@hotmail.com'; 
        $user->username = 'raygiubilo@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Giubilo'; 
        $detail->name = 'Ray'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_185.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '07206771119f7bb7b5e75ef5fd9e7368'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Beer'; 
        $detail->name = 'Andy'; 
        $detail->birthdate = '1980-02-20'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_186.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldo.tuc.ar@gmail.com'; 
        $user->username = 'arnaldo.tuc.ar@gmail.com'; 
        $user->password = '822c61e2d8dd1df84af2199b8d0bbf04'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'del carmen'; 
        $detail->name = 'arnaldo'; 
        $detail->birthdate = '1984-10-17'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_187.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rgil@paginar.net'; 
        $user->username = 'rgil@paginar.net'; 
        $user->password = '06812722ebce706e40075705cf71a997'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gil Giuliano'; 
        $detail->name = 'Rodrigo'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lfontan@paginar.net'; 
        $user->username = 'lfontan@paginar.net'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fontan'; 
        $detail->name = 'Liliana'; 
        $detail->birthdate = '1976-12-21'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_189.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'gilgiulianobackup@gmail.com'; 
        $user->username = 'gilgiulianobackup@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gil Giuliano'; 
        $detail->name = 'Rodrigo'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@yahoo.com'; 
        $user->username = 'marojenieva@yahoo.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'n'; 
        $detail->name = 'mj'; 
        $detail->birthdate = '1977-10-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_192.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marioanibalmarquez@gmail.com'; 
        $user->username = 'marioanibalmarquez@gmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'M'; 
        $detail->name = 'Mario'; 
        $detail->birthdate = '1980-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_261.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnieva@paginar.net'; 
        $user->username = 'mjnieva@paginar.net'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Paginar'; 
        $detail->name = 'Mjn'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_233.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javiromerofoto@gmail.com'; 
        $user->username = 'javiromerofoto@gmail.com'; 
        $user->password = 'b945aa0893faa7c00e33da98d4c35629'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rom'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-10-23'; 
        $detail->sex = 'M'; 
        $detail->about = 'Soy diseÃ±ador grÃ¡fico, especializado en diseÃ±o web y tambiÃ©n fotÃ³grafo de moda.'; 
        $detail->photo = 'user_195.jpg'; 
        $detail->cover_photo = 'user_195_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@gmail.com'; 
        $user->username = 'marojenieva@gmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nieva'; 
        $detail->name = 'MarÃ­a JosÃ©'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnpaginar@yahoo.com.ar'; 
        $user->username = 'mjnpaginar@yahoo.com.ar'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'hotmail paginar'; 
        $detail->name = 'mjn'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_198.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'dariozaj@gmail.com'; 
        $user->username = 'dariozaj@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Zajdenberg'; 
        $detail->name = 'Dario'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_200.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'oqtuvre@hotmail.com'; 
        $user->username = 'oqtuvre@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Stewart-Usher'; 
        $detail->name = 'Lenny'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_201.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javirangel56@gmail.com'; 
        $user->username = 'javirangel56@gmail.com'; 
        $user->password = 'ec297842d8eab5ba2e283814f582857b'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez Manteola'; 
        $detail->name = 'Javier Angel'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_202.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@me.com'; 
        $user->username = 'javierangel56@me.com'; 
        $user->password = '5d93525204a5251f56db3c39fe9dbd74'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_203.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marojenieva@gmail.com'; 
        $user->username = 'marojenieva@gmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nieva'; 
        $detail->name = 'MarÃ­a JosÃ©'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_204.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lilianafontan@hotmail.com'; 
        $user->username = 'lilianafontan@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'FontÃ¡n'; 
        $detail->name = 'Liliana'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_205.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel@fibertel.com.ar'; 
        $user->username = 'javierangel@fibertel.com.ar'; 
        $user->password = '5d93525204a5251f56db3c39fe9dbd74'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Angel Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_206.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lfontan@paginar.com'; 
        $user->username = 'lfontan@paginar.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fontan'; 
        $detail->name = 'Lili'; 
        $detail->birthdate = '1994-12-21'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_207.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fetraverso@yahoo.com.ar'; 
        $user->username = 'fetraverso@yahoo.com.ar'; 
        $user->password = '5d93525204a5251f56db3c39fe9dbd74'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Traverso'; 
        $detail->name = 'Fernando Jorge'; 
        $detail->birthdate = '1956-11-09'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_208.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '07206771119f7bb7b5e75ef5fd9e7368'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_209.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanmayol@gmail.com'; 
        $user->username = 'juanmayol@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Mayol'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_210.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sricciardi@fibertel.com.ar'; 
        $user->username = 'sricciardi@fibertel.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Lima'; 
        $detail->name = 'Sebastian'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_211.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'test@mail.com'; 
        $user->username = 'test@mail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'test'; 
        $detail->name = 'test'; 
        $detail->birthdate = '2000-04-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_212.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'test2@mail.com'; 
        $user->username = 'test2@mail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'test 2'; 
        $detail->name = 'test 2'; 
        $detail->birthdate = '1998-05-22'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_213.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sostele@outlook.com'; 
        $user->username = 'sostele@outlook.com'; 
        $user->password = '18996b4e3e882a61b88e7b1f4205bd91'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Stele'; 
        $detail->name = 'Sonia'; 
        $detail->birthdate = '1980-07-08'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_215.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'haze.cardoso@gmail.com'; 
        $user->username = 'haze.cardoso@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cardoso'; 
        $detail->name = 'Carlos'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_218.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ovidionason@gmail.com'; 
        $user->username = 'ovidionason@gmail.com'; 
        $user->password = '320173abf2ff553cf9e0ec3d06a56be2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nason'; 
        $detail->name = 'Ovidio '; 
        $detail->birthdate = '1966-11-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_219.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ovidionason1976@gmail.com'; 
        $user->username = 'ovidionason1976@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nason'; 
        $detail->name = 'Ovidio'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_220.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aldobonzi1976@gmail.com'; 
        $user->username = 'aldobonzi1976@gmail.com'; 
        $user->password = '6f7382516af91c66bf8cdd9f58ed4e43'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Bonzi'; 
        $detail->name = 'Aldo'; 
        $detail->birthdate = '1956-10-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_221.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aldobonzi1976@gmail.com'; 
        $user->username = 'aldobonzi1976@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Bonzi'; 
        $detail->name = 'Aldo'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_222.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'alainrouge1976@gmail.com'; 
        $user->username = 'alainrouge1976@gmail.com'; 
        $user->password = '8700e60bd20af1d61e93c463d46ad987'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rouge'; 
        $detail->name = 'Alain'; 
        $detail->birthdate = '1986-09-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_223.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'alainrouge1976@gmail.com'; 
        $user->username = 'alainrouge1976@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rouge'; 
        $detail->name = 'Alain'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_224.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'revistamatinee@gmail.com'; 
        $user->username = 'revistamatinee@gmail.com'; 
        $user->password = '060ed7ad35ed9c44c3fcbe3669c5e091'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Matinee'; 
        $detail->name = 'Marteena'; 
        $detail->birthdate = '1996-12-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_225.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'revistamatinee@gmail.com'; 
        $user->username = 'revistamatinee@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Matinee'; 
        $detail->name = 'Valenteena'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_226.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'jesusguiraud@yahoo.com.ar'; 
        $user->username = 'jesusguiraud@yahoo.com.ar'; 
        $user->password = 'a902e547fd00761e1a261a53382440f1'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'guiraud'; 
        $detail->name = 'jesus '; 
        $detail->birthdate = '1977-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_227.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'karaokedos@hotmail.com'; 
        $user->username = 'karaokedos@hotmail.com'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ponce'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1977-10-15'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_229.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperez@hotmail.com'; 
        $user->username = 'juanperez@hotmail.com'; 
        $user->password = '2e0d4417e261fdfc98e18976b0e7c30a'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1980-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_234.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@paginar.com'; 
        $user->username = 'lvommaro@paginar.com'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = '1982-12-20'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_235.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@paginar.net'; 
        $user->username = 'lvommaro@paginar.net'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo A.'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_236.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'karaokedos@hotmail.com'; 
        $user->username = 'karaokedos@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Hamada'; 
        $detail->name = 'Fabiana'; 
        $detail->birthdate = '1981-12-13'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_239.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'acostajuan2013@twitter.com'; 
        $user->username = 'acostajuan2013@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juan Acosta'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lvommaro@gmail.com'; 
        $user->username = 'lvommaro@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Vommaro'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_242.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'agastiazoro@paginar.com'; 
        $user->username = 'agastiazoro@paginar.com'; 
        $user->password = 'c37a5aeb20e451821854d20e76450b4b'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Ana'; 
        $detail->birthdate = '1982-04-17'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_243.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'matiasche@gmail.com'; 
        $user->username = 'matiasche@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Che'; 
        $detail->name = 'Matias'; 
        $detail->birthdate = '1984-02-19'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_245.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'nabebis@yahoo.com'; 
        $user->username = 'nabebis@yahoo.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Navas'; 
        $detail->name = 'Bea'; 
        $detail->birthdate = '1957-07-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_283.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'demians@digbang.com'; 
        $user->username = 'demians@digbang.com'; 
        $user->password = '5e0bb17463116d851353c13963fdcebe'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Schnaidman'; 
        $detail->name = 'Demian'; 
        $detail->birthdate = '1975-08-03'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_247.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'ebox@jarawi.com'; 
        $user->username = 'ebox@jarawi.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Box'; 
        $detail->name = 'Enrique'; 
        $detail->birthdate = '1975-03-20'; 
        $detail->sex = 'm'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_248.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@hotmail.com'; 
        $user->username = 'sivocarina@hotmail.com'; 
        $user->password = '6a623bdb7acd899d02439bf340d95815'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '2013-07-22'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_249.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@yahoo.com'; 
        $user->username = 'sivocarina@yahoo.com'; 
        $user->password = 'f70241431c1148ded7f71c84753de9e6'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '1968-07-22'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_251.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'jnassif@paginar.com'; 
        $user->username = 'jnassif@paginar.com'; 
        $user->password = '7bc2e834118e354b6a6819dba8853c50'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nassif'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-03-21'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_252.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.com'; 
        $user->username = 'mcarena@paginar.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Matias'; 
        $detail->birthdate = '1968-04-12'; 
        $detail->sex = 'M'; 
        $detail->about = 'EstudiÃ³ DiseÃ±o Industrial en la Universidad de Buenos Aires (UBA). EntendiÃ³ la importancia de Internet desde sus comienzos y en 1994 fundÃ³ Paginar junto a SebastiÃ¡n Tedesco. Desde entonces no ha parado. Confiesa que disfruta de la familia, los amigos, la buena cocina y el golf.'; 
        $detail->photo = 'user_253.jpg'; 
        $detail->cover_photo = 'user_253_coverphoto.jpg'; 
        $detail->save();
        $user = new User();
        $user->email = 'test@paginar.com'; 
        $user->username = 'test@paginar.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'paginar'; 
        $detail->name = 'test'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_255.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mjnieva@paginar.com'; 
        $user->username = 'mjnieva@paginar.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'FalcÃ³n'; 
        $detail->name = 'Marianita'; 
        $detail->birthdate = '2000-01-19'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_256.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'afernandez@paginar.com_1'; 
        $user->username = 'afernandez@paginar.com_1'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'del carmen'; 
        $detail->name = 'arnaldo'; 
        $detail->birthdate = '1988-08-11'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_257.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mh@illuminatilab.com'; 
        $user->username = 'mh@illuminatilab.com'; 
        $user->password = '550e04eacf97274979b28114fb818c08'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Hegouaburu'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1982-10-07'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_258.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '07206771119f7bb7b5e75ef5fd9e7368'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_259.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanaperezmilenaria2013@yahoo.com.ar'; 
        $user->username = 'juanaperezmilenaria2013@yahoo.com.ar'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juana'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_262.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->username = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Pedro'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_263.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JuanaPe20169106@twitter.com'; 
        $user->username = 'JuanaPe20169106@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juana'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_265.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fhamada@paginar.net'; 
        $user->username = 'fhamada@paginar.net'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Acosta'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = '1990-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_274.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmilenario@yahoo.com.ar'; 
        $user->username = 'juanperezmilenario@yahoo.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'yahoo!'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juan Perez'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmilenario@gmail.com'; 
        $user->username = 'juanperezmilenario@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_268.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmillonario@yahoo.com.ar'; 
        $user->username = 'juanperezmillonario@yahoo.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'NuÃ±ez AgÃ¼ero'; 
        $detail->name = 'IÃ±aki'; 
        $detail->birthdate = '1971-09-18'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_269.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->username = 'pedro.gomez2013@yahoo.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Paula'; 
        $detail->birthdate = '1995-11-19'; 
        $detail->sex = 'f'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_270.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldoprog@hotmail.com'; 
        $user->username = 'arnaldoprog@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = '1979-10-17'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_271.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JohnPerez201320@twitter.com'; 
        $user->username = 'JohnPerez201320@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Juan'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_272.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mariagomezmillonaria@gmail.com'; 
        $user->username = 'mariagomezmillonaria@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gomez'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1999-09-18'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_273.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sivocarina@gmail.com'; 
        $user->username = 'sivocarina@gmail.com'; 
        $user->password = 'f70241431c1148ded7f71c84753de9e6'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Sivo'; 
        $detail->name = 'Carina'; 
        $detail->birthdate = '1999-01-07'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_277.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mariojuarezmenor@gmail.com'; 
        $user->username = 'mariojuarezmenor@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Juarez'; 
        $detail->name = 'Mario'; 
        $detail->birthdate = '1999-09-18'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_279.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'sandrastun@gmail.com'; 
        $user->username = 'sandrastun@gmail.com'; 
        $user->password = '25af73966d487146fde66405495beda8'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'AstÃºn'; 
        $detail->name = 'Sandra Paola'; 
        $detail->birthdate = '1975-12-04'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_280.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cesaralexisdiaz@gmail.com'; 
        $user->username = 'cesaralexisdiaz@gmail.com'; 
        $user->password = 'ce8b503198ee4b1f9aed8fd1d30359a5'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'diaz'; 
        $detail->name = 'cesar alexis'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_281.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'JLuzbelito@twitter.com'; 
        $user->username = 'JLuzbelito@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'N.'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_282.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'bowieagency@twitter.com'; 
        $user->username = 'bowieagency@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Agency'; 
        $detail->name = 'Bowie'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_284.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'Jorgemantovani@hotmail.com'; 
        $user->username = 'Jorgemantovani@hotmail.com'; 
        $user->password = 'ccf14c3f2a3bb2e847546b87ccc53a78'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Mantovani'; 
        $detail->name = 'Jorge'; 
        $detail->birthdate = '1958-12-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_285.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'kbzndiaz69@yahoo.com.ar'; 
        $user->username = 'kbzndiaz69@yahoo.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Diaz'; 
        $detail->name = 'Cesar Alexis'; 
        $detail->birthdate = '1969-01-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_286.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'raygiubilo@gmail.com'; 
        $user->username = 'raygiubilo@gmail.com'; 
        $user->password = '660ce59ea0c6d08e1914f40eaaf2c93c'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'giubilo'; 
        $detail->name = 'Raymond'; 
        $detail->birthdate = '1969-12-31'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_287.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'Virtginia@twitter.com'; 
        $user->username = 'Virtginia@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ginia'; 
        $detail->name = 'Virt'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_289.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'fabianahamada@gmail.com'; 
        $user->username = 'fabianahamada@gmail.com'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Prueba'; 
        $detail->name = 'Faby'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_290.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'nocualquiera@gmail.com'; 
        $user->username = 'nocualquiera@gmail.com'; 
        $user->password = 'b94ffae584c1e0164fa01d6f47b0c094'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-06-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_291.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'virginiapizzaferri@gmail.com'; 
        $user->username = 'virginiapizzaferri@gmail.com'; 
        $user->password = 'b94ffae584c1e0164fa01d6f47b0c094'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Test'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-06-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_292.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@a.com'; 
        $user->username = 'a@a.com'; 
        $user->password = '7a54e8c15231463e5ea105e52ccc4ba2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'ss'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_293.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'b@a.com'; 
        $user->username = 'b@a.com'; 
        $user->password = '7a54e8c15231463e5ea105e52ccc4ba2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Maria'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_294.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'c@b.com'; 
        $user->username = 'c@b.com'; 
        $user->password = '7a54e8c15231463e5ea105e52ccc4ba2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Perez'; 
        $detail->name = 'Maria'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_295.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@b.com'; 
        $user->username = 'a@b.com'; 
        $user->password = '7a54e8c15231463e5ea105e52ccc4ba2'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'a'; 
        $detail->name = 'ss'; 
        $detail->birthdate = '1990-10-10'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_296.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mspentito@yahoo.com.ar'; 
        $user->username = 'mspentito@yahoo.com.ar'; 
        $user->password = '081555d77ed1f8ca02d866e40cebbc70'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Pentito'; 
        $detail->name = 'MarÃ­a Soledad'; 
        $detail->birthdate = '1978-10-15'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_297.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'vip@ideadeliveryla.com'; 
        $user->username = 'vip@ideadeliveryla.com'; 
        $user->password = 'b94ffae584c1e0164fa01d6f47b0c094'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Pizza'; 
        $detail->name = 'Virginia'; 
        $detail->birthdate = '1982-02-23'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_298.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'marianadumas@fibertel.com.ar'; 
        $user->username = 'marianadumas@fibertel.com.ar'; 
        $user->password = '19e0214bd56716066e621748149d027c'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Dumas'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1963-10-17'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_299.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldex@twitter.com'; 
        $user->username = 'arnaldex@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_302.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'vgaibisso@yahoo.com.ar'; 
        $user->username = 'vgaibisso@yahoo.com.ar'; 
        $user->password = '60107e6a39a06c573d0cb0f5d975d6f7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Gaibisso'; 
        $detail->name = 'Viviana'; 
        $detail->birthdate = '1954-09-09'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_303.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mnvercellino@hotmail.com'; 
        $user->username = 'mnvercellino@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ve.'; 
        $detail->name = 'Nawel'; 
        $detail->birthdate = '1910-09-11'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_304.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'a@a.com.ar'; 
        $user->username = 'a@a.com.ar'; 
        $user->password = 'f935802087ae35e2440da0017cda3ed7'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'a'; 
        $detail->name = 'a'; 
        $detail->birthdate = '1980-01-01'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_305.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cristobalalfonzo@outlook.com'; 
        $user->username = 'cristobalalfonzo@outlook.com'; 
        $user->password = '9f74da02dc8dd1ae9ea7bc9724715a48'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alfonzo'; 
        $detail->name = 'Cristobal'; 
        $detail->birthdate = '1996-11-10'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_306.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javiernassif@hotmail.com'; 
        $user->username = 'javiernassif@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Nassif'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '1977-03-21'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_308.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.net'; 
        $user->username = 'mcarena@paginar.net'; 
        $user->password = '9e986c4ab90ee0f951bd6bd4ce63dd12'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Mati'; 
        $detail->birthdate = '1968-12-04'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_309.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'rozashome@gmail.com'; 
        $user->username = 'rozashome@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Barton'; 
        $detail->name = 'Ed'; 
        $detail->birthdate = '1944-02-14'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_310.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'edunick@gmail.com'; 
        $user->username = 'edunick@gmail.com'; 
        $user->password = 'bac23575d826310b8c4dc501bbf28c7a'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cortez'; 
        $detail->name = 'Eduardo'; 
        $detail->birthdate = '1979-03-26'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_312.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'edunick@gmail.com'; 
        $user->username = 'edunick@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Cortez'; 
        $detail->name = 'Eduardo'; 
        $detail->birthdate = '1979-03-26'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_313.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'cperez2603@hotmail.com'; 
        $user->username = 'cperez2603@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ctez'; 
        $detail->name = 'Ealx'; 
        $detail->birthdate = '1982-11-01'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_314.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'eruete@iae.edu.ar'; 
        $user->username = 'eruete@iae.edu.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Ruete GÃ¼emes'; 
        $detail->name = 'Ernesto'; 
        $detail->birthdate = '1957-06-06'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_315.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldo.tuc.ar@gmail.com'; 
        $user->username = 'arnaldo.tuc.ar@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Fernandez'; 
        $detail->name = 'Arnaldo'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_316.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'arnaldoprog@hotmail.com'; 
        $user->username = 'arnaldoprog@hotmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'yahoo!'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Arnaldo Fernandez'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'juanperezmillonario@yahoo.com.ar'; 
        $user->username = 'juanperezmillonario@yahoo.com.ar'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'NuÃ±ez AgÃ¼ero'; 
        $detail->name = 'IÃ±aki'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_318.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'berru33@gmail.com'; 
        $user->username = 'berru33@gmail.com'; 
        $user->password = '07206771119f7bb7b5e75ef5fd9e7368'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_319.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'mcarena@paginar.net'; 
        $user->username = 'mcarena@paginar.net'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Carena'; 
        $detail->name = 'Mati'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_320.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aito0077@gmail.com'; 
        $user->username = 'aito0077@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Garcia'; 
        $detail->name = 'Leonardo'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_321.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@gmail.com'; 
        $user->username = 'javierangel56@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_323.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'daniel.riosmoreno@hotmail.com'; 
        $user->username = 'daniel.riosmoreno@hotmail.com'; 
        $user->password = '4b3768a55eef9eab907b2b1028438b45'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Rios'; 
        $detail->name = 'Daniel'; 
        $detail->birthdate = '1986-11-29'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_324.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'javierangel56@mac.com'; 
        $user->username = 'javierangel56@mac.com'; 
        $user->password = 'ec297842d8eab5ba2e283814f582857b'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Alvarez'; 
        $detail->name = 'Javier Angel '; 
        $detail->birthdate = '1956-12-08'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_325.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'aito77@twitter.com'; 
        $user->username = 'aito77@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'aito77'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'prueba@gmail.com'; 
        $user->username = 'prueba@gmail.com'; 
        $user->password = '5154783a0db328ef2d3d1ec8a2f15a5d'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Apellido'; 
        $detail->name = 'Nombre'; 
        $detail->birthdate = '1976-10-15'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_329.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'gabybreg'; 
        $user->username = 'gabybreg'; 
        $user->password = '6acdbee23196e4acff4a0df631034a89'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Brenes'; 
        $detail->name = 'Gaby'; 
        $detail->birthdate = '1990-03-30'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'myberru'; 
        $user->username = 'myberru'; 
        $user->password = '36f2e31cf9edbf4da4c6aea420894d94'; 
        $user->facebook = 'winwins'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Berruezo'; 
        $detail->name = 'Mariana'; 
        $detail->birthdate = '1972-03-29'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'NULL'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'martin@martincaputto.com'; 
        $user->username = 'martin@martincaputto.com'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Caputto'; 
        $detail->name = 'MartÃ­n'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'M'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_334.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'smoreno@paginar.net'; 
        $user->username = 'smoreno@paginar.net'; 
        $user->password = 'null'; 
        $user->facebook = 'facebook'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Moreno'; 
        $detail->name = 'Silvina'; 
        $detail->birthdate = '0000-00-00'; 
        $detail->sex = 'F'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_335.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'lmhenriquezm@gmail.com'; 
        $user->username = 'lmhenriquezm@gmail.com'; 
        $user->password = 'null'; 
        $user->facebook = 'google'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Henriquez'; 
        $detail->name = 'Luis'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'user_336.jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();
        $user = new User();
        $user->email = 'interactivista@twitter.com'; 
        $user->username = 'interactivista@twitter.com'; 
        $user->password = 'null'; 
        $user->facebook = 'twitter'; 
        $user->save();
        $detail = new UserDetail();
        $detail->user_id = $user->id;
        $detail->lastname = 'Interactivista'; 
        $detail->name = 'NULL'; 
        $detail->birthdate = 'NULL'; 
        $detail->sex = 'NULL'; 
        $detail->about = 'NULL'; 
        $detail->photo = 'jpg'; 
        $detail->cover_photo = 'NULL'; 
        $detail->save();



    /*
        "mgabrielabrenes@gmail.com","524ddb3068eafcad2df5b2fff763e898","NULL","winwins","Brenes","MarÃ­a Gabriela","1990-03-30","F","NULL","user_333.jpg","","","","NULL"
        "javierangel56@gmail.com","5d93525204a5251f56db3c39fe9dbd74","http://www.facebook.com/profile.php?id=521323328","facebook","Alvarez","Javier","1956-12-08","M","2","user_169.jpg","","","","user_169_coverphoto.jpg"
        "berru31@hotmail.com","559acdab8860f8adb906712edccf5d82","NULL","winwins","Gandhi","Super Mahatma","1969-12-31","M","NULL","user_170.jpg","","Mahatma Gandhi (Porbandar, India britÃ¡nica, 2 de octubre de 1869 â€“ Nueva Delhi, UniÃ³n de la India, 30 de enero de 1948) fue un abogado, pensador y polÃ­tico hindÃº. RecibiÃ³ de Rabindranat Tagore el nombre honorÃ­fico de Mahatma (comp. en sÃ¡nscrito e hindi de majÄ: â€˜grandeâ€™ y ÄtmÄ: â€˜almaâ€™).1 En la India tambiÃ©n se le llamaba BÄpu (àª¬àª¾àªªà«), â€˜padreâ€™ en idioma guyaratÃ­.","","user_170_coverphoto.jpg"
        "kbzndiaz69@yahoo.com.ar","e153590dbc11aefce0b910290063eb3a","NULL","winwins","Diaz","Cesar","1969-01-06","M","NULL","user_171.jpg","","","","NULL"
        "rey.nico@gmail.com","fd3c6b796a5844172f55efdb6163fb29","NULL","winwins","Rey","NicolÃ¡s","1990-10-22","M","NULL","user_173.jpg","","","","NULL"
        "bku.mberruezo@gmail.com","36f2e31cf9edbf4da4c6aea420894d94","NULL","sponsor","","HumaNet","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "ladybepalm@gmail.com","edf7a8aef0a05b73cb55e6aa840dbdb0","NULL","sponsor","","Cooperarte","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "mjnieva@paginar.net","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","Paginar","MJNieva","1977-10-29","F","1","user_180.jpg","","","","NULL"
        "marojenieva@gmail.com","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","Paginar","MJN gmail","1977-10-22","F","1","user_181.jpg","","","","NULL"
        "afernandez@paginar.net","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","del valle","arnaldo","1996-08-25","M","NULL","user_183.jpg","","alguien que hace andar las cosas...bien o mal :P","","NULL"
        "afernandez@paginar.net","49568fc397f9eb1ac2ebe28ecdc0391b","NULL","sponsor","","PatrocinadorTest","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "mjnievapaginar@twitter.com","null","http://twitter.com/account/profile?user_id=934616244","twitter","Paginar Tw","MJN","1980-10-10","F","NULL","NULL","","","","NULL"
        "pblancheton@twitter.com","null","http://twitter.com/account/profile?user_id=23941545","twitter","","pblancheton","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "rojas_alan@hotmail.com","21b027df83a8b8a2efbf195eb62f4bc9","NULL","winwins","Rojas","Alan","1983-12-29","M","2","user_214.jpg","","","","NULL"
        "apiccardo@outlook.com","3a17bbd8b50683897e9b826646c251ba","NULL","winwins","Piccardo","Adriana","1958-08-10","F","1","user_216.jpg","Buenos Aires","","","NULL"
        "antoniofilardi1976@gmail.com","null","http://www.facebook.com/profile.php?id=100003482254376","facebook","Rojas","Alan","1983-12-29","M","2","user_217.jpg","","","","NULL"
        "LVommaro@twitter.com","null","http://twitter.com/account/profile?user_id=110222106","twitter","Vommaro","Leonardo","1982-12-20","M","2","user_238.jpg","","","","NULL"
        "lvommaro@gmail.com","null","http://www.facebook.com/profile.php?id=523066964","facebook","Vommaro","Leonardo","1982-12-20","NULL","NULL","user_237.jpg","","","","NULL"
        "clarisaruizdiaz@gmail.com","193f0d0cc841fc074035c9fb566d79a0","NULL","winwins","WW","Clarisa","2013-05-29","F","NULL","user_228.jpg","Bs As","","","user_228_coverphoto.jpg"
        "mjnieva@paginar.com","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","n","mj","1980-01-22","F","NULL","user_230.jpg","","","","NULL"
        "clarisaruizdiaz@yahoo.com.ar","193f0d0cc841fc074035c9fb566d79a0","NULL","winwins","WW","Clari","2013-06-01","F","NULL","user_231.jpg","","","","user_231_coverphoto.jpg"
        "Myberru@twitter.com","null","http://twitter.com/account/profile?user_id=174686940","twitter","berru","My","1990-09-25","F","NULL","user_241.jpg","","esta es mi cuenta en WW de twitter","","user_241_coverphoto.jpg"
        "karaokedos@hotmail.com","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","sponsor","","Prueba","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "clarisaruizdiaz@hotmail.com","193f0d0cc841fc074035c9fb566d79a0","NULL","winwins","Win","Clari","2013-07-02","F","NULL","user_246.jpg","","","","user_246_coverphoto.jpg"
        "sivocarina@yahoo.com","f70241431c1148ded7f71c84753de9e6","NULL","winwins","Sivo","Carina","1978-07-22","F","1","user_250.jpg","BA","","","user_250_coverphoto.jpg"
        "martin@MejoramosJuntos.org","c67069101b9d0e33d072a8e5b2f4b2cf","NULL","winwins","Urdaniz","Martin","1963-09-26","M","1","user_254.jpg","","","","NULL"
        "clarisa@winwins.org","193f0d0cc841fc074035c9fb566d79a0","NULL","winwins","WinWin","Clarisa","1990-09-07","F","NULL","user_260.jpg","","","","user_260_coverphoto.jpg"
        "agus@toma78.com","null","http://www.facebook.com/profile.php?id=100002436903359","facebook","Berruezo","Agustin","1974-01-20","NULL","NULL","user_264.jpg","","","","NULL"
        "afernandez@paginar.com","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","mini","arnaldo","1997-10-21","M","NULL","user_276.jpg","","","","NULL"
        "fhamada@paginar.com","f935802087ae35e2440da0017cda3ed7","NULL","winwins","Zimmerman Puentedura","MarÃ­a Elizabeth","1980-10-10","F","NULL","user_278.jpg","","","","NULL"
        "berru33@gmail.com","5796eeb38c008416c4856437434678fb","NULL","sponsor","","Patrocinador A","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "javiernassif@hotmail.com","706ca0a2ae8e1f3651932b8a6fa7735d","NULL","winwins","Nassif","Javier","1977-03-21","M","1","user_300.jpg","","","","NULL"
        "alexcarri@gmail.com","eb1f416487404b3a0474053b2c0d9471","NULL","winwins","Carrillo","Alejandro","1954-01-31","M","1","user_301.jpg","","","","user_301_coverphoto.jpg"
        "alficarr2@gmail.com","70c51c5059b92e34996ee71f692899ca","NULL","winwins","Carr","Alfonzo","1992-07-10","M","NULL","user_307.jpg","","","","NULL"
        "maticarena@gmail.com","5154783a0db328ef2d3d1ec8a2f15a5d","NULL","winwins","CarenaGmail","MatiasGmail","1967-09-04","M","NULL","user_311.jpg","","","","NULL"
        "cesaralexisdiaz@gmail.com","4c7057915afaff676c3703848d6f508f","NULL","sponsor","","Nuevo Patro Cesar","NULL","NULL","NULL","NULL","NULL","NULL","NULL","NULL"
        "gabybreg@twitter.com","null","http://twitter.com/account/profile?user_id=30817249","twitter","Brenes","Gaby","1990-03-30","F","NULL","user_326.jpg","","","","NULL"
        "daniel.riosmoreno@hotmail.com","null","http://www.facebook.com/profile.php?id=10152308066260143","facebook","Rios","Daniel","0000-00-00","M","2","user_327.jpg","CABA","","","user_327_coverphoto.jpg"
        "numa@gopacifia.org","aa6d2727d042f6c1fab79cb2b6fa29d7","NULL","winwins","Bellisario","Numa","1983-07-30","M","NULL","user_331.jpg","","","","NULL"
        */
    }

}

