.env.example
.gitattributes
.gitignore
_ide_helper.php
app/Commands/Command.php
app/Console/Commands/Inspire.php
app/Console/Kernel.php
#	new file:   app/Events/Event.php
#	new file:   app/Exceptions/Handler.php
#	new file:   app/Handlers/Commands/.gitkeep
#	new file:   app/Handlers/Events/.gitkeep
#	new file:   app/Http/Controllers/Controller.php
#	new file:   app/Http/Kernel.php
#	new file:   app/Http/Middleware/Authenticate.php
#	new file:   app/Http/Middleware/RedirectIfAuthenticated.php
#	new file:   app/Http/Middleware/VerifyCsrfToken.php
#	new file:   app/Http/Requests/Request.php
#	new file:   app/Http/routes.php
#	new file:   app/Providers/AppServiceProvider.php
#	new file:   app/Providers/BusServiceProvider.php
#	new file:   app/Providers/ConfigServiceProvider.php
#	new file:   app/Providers/EventServiceProvider.php
#	new file:   app/Providers/RouteServiceProvider.php
#	new file:   app/Services/Registrar.php
#	new file:   app/User.php
#	new file:   app/helpers.php
#	new file:   artisan
#	new file:   bootstrap/app.php
#	new file:   bootstrap/autoload.php
#	new file:   composer.json
#	new file:   composer.lock
#	new file:   config/app.php
#	new file:   config/auth.php
#	new file:   config/cache.php
#	new file:   config/compile.php
#	new file:   config/cors.php
#	new file:   config/database.php
#	new file:   config/filesystems.php
#	new file:   config/jwt.php
#	new file:   config/mail.php
#	new file:   config/queue.php
#	new file:   config/services.php
#	new file:   config/session.php
#	new file:   config/view.php
#	new file:   database/.gitignore
#	new file:   database/migrations/.gitkeep
#	new file:   database/migrations/2014_10_12_000000_create_users_table.php
#	new file:   database/migrations/2014_10_12_100000_create_password_resets_table.php
#	new file:   database/seeds/.gitkeep
#	new file:   database/seeds/DatabaseSeeder.php
#	new file:   gulpfile.js
#	new file:   package.json
#	new file:   phpspec.yml
#	new file:   phpunit.xml
#	new file:   public/.htaccess
#	new file:   public/css/app.css
#	new file:   public/css/bootstrap.superhero.min.css
#	new file:   public/favicon.ico
#	new file:   public/fonts/glyphicons-halflings-regular.eot
#	new file:   public/fonts/glyphicons-halflings-regular.svg
#	new file:   public/fonts/glyphicons-halflings-regular.ttf
#	new file:   public/fonts/glyphicons-halflings-regular.woff
#	new file:   public/fonts/glyphicons-halflings-regular.woff2
#	new file:   public/index.php
#	new file:   public/lib/loading-bar.css
#	new file:   public/lib/loading-bar.js
#	new file:   public/lib/ngStorage.js
#	new file:   public/partials/home.html
#	new file:   public/partials/restricted.html
#	new file:   public/partials/signin.html
#	new file:   public/partials/signup.html
#	new file:   public/robots.txt
#	new file:   public/scripts/app.js
#	new file:   public/scripts/controllers.js
#	new file:   public/scripts/services.js
#	new file:   readme.md
#	new file:   remove.leo
#	new file:   resources/assets/less/app.less
#	new file:   resources/assets/less/bootstrap/alerts.less
#	new file:   resources/assets/less/bootstrap/badges.less
#	new file:   resources/assets/less/bootstrap/bootstrap.less
#	new file:   resources/assets/less/bootstrap/breadcrumbs.less
#	new file:   resources/assets/less/bootstrap/button-groups.less
#	new file:   resources/assets/less/bootstrap/buttons.less
#	new file:   resources/assets/less/bootstrap/carousel.less
#	new file:   resources/assets/less/bootstrap/close.less
#	new file:   resources/assets/less/bootstrap/code.less
#	new file:   resources/assets/less/bootstrap/component-animations.less
#	new file:   resources/assets/less/bootstrap/dropdowns.less
#	new file:   resources/assets/less/bootstrap/forms.less
#	new file:   resources/assets/less/bootstrap/glyphicons.less
#	new file:   resources/assets/less/bootstrap/grid.less
#	new file:   resources/assets/less/bootstrap/input-groups.less
#	new file:   resources/assets/less/bootstrap/jumbotron.less
#	new file:   resources/assets/less/bootstrap/labels.less
#	new file:   resources/assets/less/bootstrap/list-group.less
#	new file:   resources/assets/less/bootstrap/media.less
#	new file:   resources/assets/less/bootstrap/mixins.less
#	new file:   resources/assets/less/bootstrap/mixins/alerts.less
#	new file:   resources/assets/less/bootstrap/mixins/background-variant.less
#	new file:   resources/assets/less/bootstrap/mixins/border-radius.less
#	new file:   resources/assets/less/bootstrap/mixins/buttons.less
#	new file:   resources/assets/less/bootstrap/mixins/center-block.less
#	new file:   resources/assets/less/bootstrap/mixins/clearfix.less
#	new file:   resources/assets/less/bootstrap/mixins/forms.less
#	new file:   resources/assets/less/bootstrap/mixins/gradients.less
#	new file:   resources/assets/less/bootstrap/mixins/grid-framework.less
#	new file:   resources/assets/less/bootstrap/mixins/grid.less
#	new file:   resources/assets/less/bootstrap/mixins/hide-text.less
#	new file:   resources/assets/less/bootstrap/mixins/image.less
#	new file:   resources/assets/less/bootstrap/mixins/labels.less
#	new file:   resources/assets/less/bootstrap/mixins/list-group.less
#	new file:   resources/assets/less/bootstrap/mixins/nav-divider.less
#	new file:   resources/assets/less/bootstrap/mixins/nav-vertical-align.less
#	new file:   resources/assets/less/bootstrap/mixins/opacity.less
#	new file:   resources/assets/less/bootstrap/mixins/pagination.less
#	new file:   resources/assets/less/bootstrap/mixins/panels.less
#	new file:   resources/assets/less/bootstrap/mixins/progress-bar.less
#	new file:   resources/assets/less/bootstrap/mixins/reset-filter.less
#	new file:   resources/assets/less/bootstrap/mixins/resize.less
#	new file:   resources/assets/less/bootstrap/mixins/responsive-visibility.less
#	new file:   resources/assets/less/bootstrap/mixins/size.less
#	new file:   resources/assets/less/bootstrap/mixins/tab-focus.less
#	new file:   resources/assets/less/bootstrap/mixins/table-row.less
#	new file:   resources/assets/less/bootstrap/mixins/text-emphasis.less
#	new file:   resources/assets/less/bootstrap/mixins/text-overflow.less
#	new file:   resources/assets/less/bootstrap/mixins/vendor-prefixes.less
#	new file:   resources/assets/less/bootstrap/modals.less
#	new file:   resources/assets/less/bootstrap/navbar.less
#	new file:   resources/assets/less/bootstrap/navs.less
#	new file:   resources/assets/less/bootstrap/normalize.less
#	new file:   resources/assets/less/bootstrap/pager.less
#	new file:   resources/assets/less/bootstrap/pagination.less
#	new file:   resources/assets/less/bootstrap/panels.less
#	new file:   resources/assets/less/bootstrap/popovers.less
#	new file:   resources/assets/less/bootstrap/print.less
#	new file:   resources/assets/less/bootstrap/progress-bars.less
#	new file:   resources/assets/less/bootstrap/responsive-embed.less
#	new file:   resources/assets/less/bootstrap/responsive-utilities.less
#	new file:   resources/assets/less/bootstrap/scaffolding.less
#	new file:   resources/assets/less/bootstrap/tables.less
#	new file:   resources/assets/less/bootstrap/theme.less
#	new file:   resources/assets/less/bootstrap/thumbnails.less
#	new file:   resources/assets/less/bootstrap/tooltip.less
#	new file:   resources/assets/less/bootstrap/type.less
#	new file:   resources/assets/less/bootstrap/utilities.less
#	new file:   resources/assets/less/bootstrap/variables.less
#	new file:   resources/assets/less/bootstrap/wells.less
#	new file:   resources/lang/en/pagination.php
#	new file:   resources/lang/en/passwords.php
#	new file:   resources/lang/en/validation.php
#	new file:   resources/views/emails/password.blade.php
#	new file:   resources/views/errors/503.blade.php
#	new file:   resources/views/spa.blade.php
#	new file:   resources/views/vendor/.gitkeep
#	new file:   server.php
#	new file:   storage/.gitignore
#	new file:   storage/app/.gitignore
#	new file:   storage/framework/.gitignore
#	new file:   storage/framework/cache/.gitignore
#	new file:   storage/framework/sessions/.gitignore
#	new file:   storage/framework/views/.gitignore
#	new file:   storage/logs/.gitignore
#	new file:   tests/ExampleTest.php
#	new file:   tests/TestCase.php
#
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	deleted:    public/css/app.css
#	deleted:    public/css/bootstrap.superhero.min.css
#	deleted:    public/favicon.ico
#	deleted:    public/fonts/glyphicons-halflings-regular.eot
#	deleted:    public/fonts/glyphicons-halflings-regular.svg
#	deleted:    public/fonts/glyphicons-halflings-regular.ttf
#	deleted:    public/fonts/glyphicons-halflings-regular.woff
#	deleted:    public/fonts/glyphicons-halflings-regular.woff2
#	deleted:    public/lib/loading-bar.css
#	deleted:    public/lib/loading-bar.js
#	deleted:    public/lib/ngStorage.js
#	modified:   public/partials/home.html
#	deleted:    public/partials/restricted.html
#	deleted:    public/partials/signin.html
#	modified:   public/partials/signup.html
#	deleted:    public/scripts/app.js
#	deleted:    public/scripts/controllers.js
#	deleted:    public/scripts/services.js
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
app/Model/ database/migrations/.2014_10_12_000000_create_users_table.php.swp database/migrations/.2015_05_15_173941_create_winwins_table.php.swp database/migrations/2015_05_15_173941_create_winwins_table.php database/migrations/2015_05_15_173947_create_groups_table.php public/app.js public/controllers/ public/directives/ public/favicon.png public/index.html public/partials/login.html public/partials/profile.html public/services/ public/stylesheets/ public/vendor/
